insert into user_auth_type (user_id, user_type_user_type_id) VALUES (1,1);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (2, 1);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (3, 1);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (4, 1);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (5, 1);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (6, 2);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (7, 2);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (8, 2);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (9, 2);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (10, 2);
insert into user_auth_type (user_id, user_type_user_type_id) VALUES (10, 3);